"use client";

import * as React from "react";
import { useTheme } from "next-themes";

import { cn } from "@/lib/utils";

let idCounter = 0;

const lightVars = {
  background: "transparent",
  primaryColor: "#ecfdf5",
  primaryBorderColor: "#34d399",
  primaryTextColor: "#052e1f",
  secondaryColor: "#f0fdfa",
  secondaryBorderColor: "#5eead4",
  tertiaryColor: "#f7fee7",
  tertiaryBorderColor: "#a3e635",
  lineColor: "#94a3b8",
  textColor: "#334155",
  clusterBkg: "rgba(16,185,129,0.06)",
  clusterBorder: "#a7f3d0",
};

const darkVars = {
  background: "transparent",
  primaryColor: "#064e3b",
  primaryBorderColor: "#34d399",
  primaryTextColor: "#d1fae5",
  secondaryColor: "#134e4a",
  secondaryBorderColor: "#2dd4bf",
  tertiaryColor: "#1a2e05",
  tertiaryBorderColor: "#84cc16",
  lineColor: "#64748b",
  textColor: "#cbd5e1",
  clusterBkg: "rgba(52,211,153,0.08)",
  clusterBorder: "#065f46",
};

export function Mermaid({ chart, className }: { chart: string; className?: string }) {
  const { resolvedTheme } = useTheme();
  const [svg, setSvg] = React.useState<string>("");
  const [error, setError] = React.useState(false);
  const code = chart.trim();

  React.useEffect(() => {
    let cancelled = false;
    const isDark = resolvedTheme === "dark";

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "loose",
          theme: "base",
          themeVariables: {
            fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui",
            fontSize: "14px",
            ...(isDark ? darkVars : lightVars),
          },
        });
        const id = `mmd-${(idCounter += 1)}`;
        const { svg: rendered } = await mermaid.render(id, code);
        if (!cancelled) {
          setSvg(rendered);
          setError(false);
        }
      } catch {
        if (!cancelled) setError(true);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, resolvedTheme]);

  if (error) {
    return (
      <pre className="overflow-x-auto rounded-lg bg-muted p-4 text-xs text-muted-foreground">
        {code}
      </pre>
    );
  }

  return (
    <div
      className={cn(
        "mermaid-rendered flex justify-center overflow-x-auto py-2",
        !svg && "min-h-24 animate-pulse rounded-lg bg-muted/50",
        className,
      )}
      // SVG is generated by mermaid from authored, trusted content.
      dangerouslySetInnerHTML={svg ? { __html: svg } : undefined}
    />
  );
}
